fixtures:
  repositories:
    apache: https://github.com/evenup/evenup-apache.git
    concat: git://github.com/ripienaar/puppet-concat.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    kibana: "#{source_dir}"

