---
  .travis.yml:
    hc_secure: "aRJ187uJZQ8JtMyFZbcDXTpgMUCkcs0gY3sn/uzowZIAKLXECvHE43rG5/VWBC9uWrv5d4q5U8AANPgVZpBZyt9UUFR9FSXRtd3skuP/SqS4nt31SlF52lWiq0dFje/mpuBvAsoV3xD/nQgIzxPT/sWfDlpGHF5TvLG8AXbFrKU="

